spring.application.name=payzzle

spring.datasource.url=jdbc:postgresql://localhost:32768/payzzle
spring.datasource.username=
spring.datasource.password=

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
